### ISSUE TITLE
运行测试脚本时报错！

### ISSUE THREAD

**Issue by chen1234520** [Ranchentx/EFGRNet#3]
RuntimeError: max_pool2d_with_indices_out_cuda_frame failed with error code 0
  File "/data_1/software/yes/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 488, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: **max_pool2d_with_indices_out_cuda_frame failed with error code 0**
请问，这是什么原因导致呢？测试图像需要提前resize到320*320尺寸才能用吗？

**Comment by chen1234520** [comment]
/data_1/deep_learning_layer/layer/pytorch/EFGRNet/configs/config.py:236: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = AttrDict(yaml.load(f))
/data_1/deep_learning_layer/layer/pytorch/EFGRNet/models/model_helper.py:25: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(m.state_dict()[key], mode='fan_out')
im_detect: 1/12866 6.144359s 0.317099s 0.024s
Traceback (most recent call last):
  File "eval_dcn.py", line 223, in <module>
    main()
  File "eval_dcn.py", line 218, in main
    batch_size=batch_size)
  File "eval_dcn.py", line 96, in eval_net
    output= net(x)
  File "/data_1/software/yes/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data_1/deep_learning_layer/layer/pytorch/EFGRNet/models/model_builder_vgg.py", line 207, in forward
    arm_xs, odm_xs = self.extractor(input)
  File "/data_1/software/yes/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data_1/deep_learning_layer/layer/pytorch/EFGRNet/models/efrgnet_vgg.py", line 317, in forward
    x_pool1 = self.impn1(x)
  File "/data_1/software/yes/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data_1/deep_learning_layer/layer/pytorch/EFGRNet/models/efrgnet_vgg.py", line 108, in forward
    out = self.single_branch(x)
  File "/data_1/software/yes/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data_1/software/yes/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 141, in forward
    self.return_indices)
  File "/data_1/software/yes/envs/pytorch/lib/python3.6/site-packages/torch/_jit_internal.py", line 138, in fn
    return if_false(*args, **kwargs)
  File "/data_1/software/yes/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 488, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: max_pool2d_with_indices_out_cuda_frame failed with error code 0

**Comment by chen1234520** [comment]
Thank you very much if you can help me！
